# Generated by Django 3.1.3 on 2020-11-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20201122_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='students',
            name='updated_at',
        ),
    ]
