# Generated by Django 3.1.3 on 2020-11-23 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_absent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absent',
            name='absentst',
        ),
    ]
